const host = "http://localhost:3090";
export const RegisterRoute=`${host}/register`;
export const issueRoute=`${host}/api/issues`;
export const refreshTokenRoute=`${host}/refresh`;   
export const loginRoute=`${host}/login`;
export const addLabRoute=`${host}/addLab`;
export const getDataRoute=`${host}/getLab`;
export const getUserIssueRoute = `${host}/api/issues/userIssue`;
export const handleResolveRoute = `${host}/api/issues/resolve`;
